In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Titanic.csv")

In [3]:
df.head()

      sex   age  sibsp  parch     fare embarked  class    who  alone  survived
0    male  22.0      1      0   7.2500        S  Third    man  False         0
1  female  38.0      1      0  71.2833        C  First  woman  False         1
2  female  26.0      0      0   7.9250        S  Third  woman   True         1
3  female  35.0      1      0  53.1000        S  First  woman  False         1
4    male  35.0      0      0   8.0500        S  Third    man   True         0

In [4]:
df.tail()

,sex,age,sibsp,parch,fare,embarked,class,who,alone,survived
886,male,27.0,0,0,13.00,S,Second,man,True,0
887,female,19.0,0,0,30.00,S,First,woman,True,1
888,female,NaN,1,2,23.45,S,Third,woman,False,0
889,male,26.0,0,0,30.00,C,First,man,True,1
890,male,32.0,0,0,7.75,Q,Third,man,True,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sex       891 non-null    object
 1   age       714 non-null    float64
 2   sibsp     891 non-null    int64
 3   parch     891 non-null    int64
 4   fare      891 non-null    float64
 5   embarked  889 non-null    object
 6   class     891 non-null    object
 7   who       891 non-null    object
 8   alone     891 non-null    bool
 9   survived  891 non-null    int64
dtypes: bool(1), float64(2), int64(3), object(4)
memory usage: 63.6+ KB

In [7]:
df.shape

(891, 10)

In [9]:
df.isnull().sum()

sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
class         0
who           0
alone         0
survived      0
dtype: int64

In [11]:
print(df.columns)

Index(['sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who',
       'alone', 'survived'],
      dtype='object')

In [12]:
df["age"] = df["age"].fillna(df["age"].median())
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [13]:
df.duplicated().sum()

np.int64(116)

In [14]:
df=df.drop_duplicates()

In [16]:
df.dtypes

sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
class        object
who          object
alone          bool
survived      int64
dtype: object

In [17]:
df.describe()

              age       sibsp       parch        fare    survived
count  775.000000  775.000000  775.000000  775.000000  775.000000
mean    29.581187    0.529032    0.420645   34.878403    0.412903
std     13.766359    0.990326    0.840565   52.408474    0.492674
min      0.420000    0.000000    0.000000    0.000000    0.000000
25%     21.000000    0.000000    0.000000    8.050000    0.000000
50%     28.000000    0.000000    0.000000   15.900000    0.000000
75%     36.000000    1.000000    1.000000   34.197900    1.000000
max     80.000000    8.000000    6.000000  512.329200    1.000000

In [18]:
df.mean(numeric_only=True)

age         29.581187
sibsp        0.529032
parch        0.420645
fare        34.878403
alone        0.563871
survived     0.412903
dtype: float64

In [19]:
df.median(numeric_only=True)

age         28.0
sibsp        0.0
parch        0.0
fare        15.9
alone        1.0
survived     0.0
dtype: float64

In [21]:
df["sex"].value_counts()

sex
male      483
female    292
Name: count, dtype: int64

In [24]:
df["class"].value_counts()

class
Third     401
First     210
Second    164
Name: count, dtype: int64

In [25]:
df.to_csv("cleaned_titanic.csv", index=False)

In [26]:
from google.colab import files
files.download("cleaned_titanic.csv")

Data Cleaning & Exploration Report
Dataset: Titanic Dataset
Objective: To clean and explore the Titanic dataset using the Pandas library for Data preprocessingand exploratory data analysis.
Steps Performed:
Loaded the Titanic CSV dataset.
Displayed the first five rows.
Checked dataset information.
Identified missing values.
Filled missing values in the age and embarked columns.
Checked and removed duplicate records.
Displayed summary statistics.
Calculated the mean and median of numerical columns.
Counted passengers by gender (sex) and travel class (class).
Saved the cleaned dataset.
Conclusion:
The Titanic dataset was successfully cleaned and explored using Pandas. Missing values and duplicate records were handled, and basic statistical analysis was performed. The cleaned dataset is now ready for further data analysis and machine learning tasks.